logging:
    level:
        root: DEBUG
        org:
            springframework:
                boot:
                    actuate: DEBUG
                security:
                    access: DEBUG
                    oauth2: DEBUG
                web:
                    filter: DEBUG
server:
    port: 9091
spring:
    datasource:
        url: jdbc:postgresql://localhost:5433/makromapa-auth-dev
    flyway:
        locations:
            - classpath:db/migration/default
            - classpath:db/migration/local
            - classpath:db/migration/test-data
