## How to submit:$
#  gcloud builds submit --config cicd/cloudbuild-pr-banches.yml .
##
steps:

  #
  # Build the project
  #
  - name: 'openjdk:17-oraclelinux8'
    id: build_jar
    args: ["./gradlew", "clean", "build", "-x", "test"]

  #
  # Unit test
  #
  - name: 'openjdk:17-oraclelinux8'
    id: unit_test
    args: ["./gradlew", "test"]
    waitFor:
      - build_jar

  #
  # integration test
  #
  - name: 'docker/compose:1.29.2'
    id: postgres_db
    args: ['-f', 'cicd/docker-compose.cicd.dependencies.yml', "up", "-d"]
    env:
      - 'PROJECT_ID=$PROJECT_ID'
    waitFor:
      - unit_test

  - name: 'openjdk:17-oraclelinux8'
    id: integration_test
    args: [ "./gradlew", "integrationTest", "-Pprofiles=integrationTest,cicd", "-i" ]
    env: [ 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/makromapa-auth-dev',
           "-XX:MaxDirectMemorySize=100MB" ]
    waitFor:
      - postgres_db

timeout: 1800s
