version: '3.7'
services:
  makromapa_auth_db:
    image: postgres:12
    restart: always

    expose:
      - 5433

    ports:
      - 5433:5432

    environment:
      - POSTGRES_DB=makromapa-db-auth
      - POSTGRES_USER=makromapa-auth-user
      - POSTGRES_PASSWORD=mysecretpassword

    networks:
      main:
        aliases:
          - postgres_db

networks:
  main:
    driver: bridge
