version: '3.7'
services:
  postgres_db:
    image: postgres:12
    restart: always

    expose:
      - 5442

    ports:
      - 5432:5432

    environment:
      - POSTGRES_DB=makromapa-db-auth
      - POSTGRES_USER=makromapa-db-user
      - POSTGRES_PASSWORD=mysecretpassword

    networks:
      main:
        aliases:
          - postgres_db

networks:
  main:
    driver: bridge
