name: Build & Test

on:
  push:
    branches: [ master, test ]

env:
  PROJECT_ID: makromapa-338723

jobs:
  build:
    name: build changes
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: 'gradle'
    - name: Build without tests
      uses: gradle/gradle-build-action@v2
      with:
        arguments: clean build -x test

    - uses: actions/upload-artifact@v2
      with:
        name: build-artifactory
        path: build/
        retention-days: 1


  unit-test:
    name: test changes
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: 'actions/checkout@v2'
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'
      - uses: 'actions/download-artifact@v2'

      - name: Run Unit Tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: build

    services:
      postgres_db:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: makromapa-db-dev
          POSTGRES_USER: makromapa-auth-user
          POSTGRES_PASSWORD: mysecretpassword

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: 'actions/checkout@v2'
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'
      - uses: 'actions/download-artifact@v2'

      - name: Run Integration Tests
        uses: gradle/gradle-build-action@v2
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://127.0.0.1:5432/makromapa-db-dev
        with:
          arguments: integrationTest -Pprofiles=integrationTest,cicd

  build-push-docker:
    name: build and push docker image to GCP Repository
    runs-on: ubuntu-latest
    needs: [integration-tests, unit-test]

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v2'

      - uses: 'actions/download-artifact@v2'
        with:
          name: build-artifactory
          path: build/

      - uses: madhead/read-java-properties@latest
        id: version
        with:
          file: gradle.properties
          property: version
          default: 0.0.1

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.GPC_CREDENTIALS_JSON }}'

      - run: |-
          gcloud --quiet auth configure-docker

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      #- name: Get the GKE credentials so we can deploy to the cluster
      #  uses: google-github-actions/get-gke-credentials
      #    with:
      #      cluster_name: ${{ env.GKE_CLUSTER }}
      #      location: ${{ env.GKE_ZONE }}
      #      credentials: ${{ secrets.GKE_SA_KEY }}

      # Build the Docker image
      - name: Build
        run: |-
          echo "Project: $PROJECT_ID" ${{ steps.all.outputs.version }}
          docker build \
            --tag "gcr.io/$PROJECT_ID/makromapa-auth:${{ steps.all.outputs.version }}-${GITHUB_SHA::7}" \
            --build-arg COMMIT_SHA=${GITHUB_SHA::7} \
            .

      # Push the Docker image to Google Container Registry
      - name: Publish
        run: |-
          docker push "gcr.io/$PROJECT_ID/makromapa-auth:${{ steps.all.outputs.version }}-${GITHUB_SHA::7}"
