name: Build & Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, test ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: 'gradle'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper         
    - name: Build without tests
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper
        arguments: clean build -x test
  
  test: 
    needs: build
    runs-on: ubuntu-latest
    
    services: 
      postgres_db: 
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: makromapa-db-dev
          POSTGRES_USER: makromapa-auth-user
          POSTGRES_PASSWORD: mysecretpassword
        
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    steps:
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: 'gradle'
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper         
    - name: Run Unit Tests
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper
        arguments: test
    - name: Run Integration Tests
      uses: gradle/gradle-build-action@v2
      env: 
          SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/makromapa-db-dev
      with:
        gradle-version: wrapper
        arguments: integrationTest -Pprofiles=integrationTest,cicd
