name: Build & Test

on:
  push:
    branches: [ master, test ]

jobs:
  build:
    name: build changes
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: 'gradle'
    - name: Build without tests
      uses: gradle/gradle-build-action@v2
      with:
        arguments: clean build -x test

    - uses: actions/upload-artifact@v2
      with:
        name: build-artifactory
        path: build/
        retention-days: 1

  unit-test:
    name: test changes
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: 'actions/checkout@v3'
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'
      - uses: 'actions/download-artifact@v2'

      - name: Run Unit Tests
        uses: gradle/gradle-build-action@v2
        with:
          arguments: test

  integration-tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: build

    services:
      postgres_db:
        image: postgres:13
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: makromapa-db-dev
          POSTGRES_USER: makromapa-auth-user
          POSTGRES_PASSWORD: mysecretpassword

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: 'actions/checkout@v3'
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: 'gradle'
      - uses: 'actions/download-artifact@v2'

      - name: Run Integration Tests
        uses: gradle/gradle-build-action@v2
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://127.0.0.1:5432/makromapa-db-dev
        with:
          arguments: integrationTest -Pprofiles=integrationTest,cicd

  build-push-docker:
    name: build and push docker image to GCP Repository
    runs-on: ubuntu-latest
    needs: [integration-tests, unit-test]
    outputs:
      appVersion: ${{ steps.build_image.outputs.value }}
    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - uses: 'actions/checkout@v3'

      - uses: 'actions/download-artifact@v2'
        with:
          name: build-artifactory
          path: build/

      - uses: madhead/read-java-properties@latest
        id: version
        with:
          file: gradle.properties
          property: version
          default: 0.0.1

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: access_token
          workload_identity_provider: '${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}'
          service_account: '${{ secrets.GPC_SERVICE_ACCOUNT }}'
          access_token_lifetime: 300s

      - name: Login to Artifact Registry
        uses: docker/login-action@v1
        with:
          registry: europe-central2-docker.pkg.dev
          username: oauth2accesstoken
          password: ${{ steps.auth.outputs.access_token }}

      - id: 'docker-login'
        run: "gcloud auth configure-docker"

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: "Build Docker Image"
        id: build_image
        run: |-
          PROJECT_ID="${{ secrets.GCP_PROJECT_ID }}"
          echo "Project: $PROJECT_ID, version: ${{ steps.version.outputs.value }}"
          
          APP_VERSION="${{ steps.version.outputs.value }}-${GITHUB_SHA::7}"
          echo "::set-output name=appVersion::$(echo $APP_VERSION)"
          run: echo "appVersion=$APP_VERSION" >> $GITHUB_OUTPUT
          
          
          docker build \
            --tag "europe-central2-docker.pkg.dev/$PROJECT_ID/makromapa-auth:${APP_VERSION}" \
            --build-arg COMMIT_SHA=${GITHUB_SHA::7} \
            .

      - name: "Push the Docker image to Google Container Registry"
        run: |-
          PROJECT_ID="${{ secrets.GCP_PROJECT_ID }}"
          docker push "europe-central2-docker.pkg.dev/$PROJECT_ID/makromapa-auth:${{ steps.build_image.outputs.appVersion }}"


  update-chart-repository:
    name: Update Helm Template with new version
    runs-on: ubuntu-latest
    needs: [build-push-docker]

    steps:
      - name: "Checkout the DevOps Repository, to update Kubernetes Chart AppVersion"
        uses: 'actions/checkout@v3'
        with:
          repository: C0deH0use/devops
          ref: main
          token: ${{ secrets.DEVOPS_GITHUB_TOKEN }}
          path: devops

      - name: "Update Chart version"
        uses: mikefarah/yq@master
        with:
          cmd: NEW_APP_VERSION="${{ needs.build-push-docker.outputs.appVersion }}" yq -i '.appVersion = strenv(NEW_APP_VERSION)' devops/k8s/Charts/backend-service/Chart.yaml

      - name: "Check New Chart version"
        id: "new_chart_version"
        uses: mikefarah/yq@master
        with:
          cmd: yq '.appVersion' devops/k8s/Charts/auth-service/Chart.yaml

      - run: echo "Chart new version ${{ steps.new_chart_version.outputs.result }}"

      - name: Commit report
        run: |
          cd  devops
          git config --global user.name 'DevOps BOT'
          git config --global user.email 'bot@code-house.pl'
          git commit -am "Update MakroMapa Auth Chart version"
          git push
